<?php

use Kirby\Cms\App;

App::plugin(
    name: 'bnomei/kart',
    extends: [
        'snippets' => [
            'kart/account-delete' => __DIR__.'/snippets/kart/account-delete.php',
            'kart/captcha' => __DIR__.'/snippets/kart/captcha.php',
            'kart/cart' => __DIR__.'/snippets/kart/cart.php',
            'kart/cart-add' => __DIR__.'/snippets/kart/cart-add.php',
            'kart/cart-buy' => __DIR__.'/snippets/kart/cart-buy.php',
            'kart/checkout-json-ld' => __DIR__.'/snippets/kart/checkout-json-ld.php',
            'kart/email-login-magic' => __DIR__.'/snippets/kart/email-login-magic.php',
            'kart/email-login-magic.html' => __DIR__.'/snippets/kart/email-login-magic.html.php',
            'kart/input-csrf' => __DIR__.'/snippets/kart/input-csrf.php',
            'kart/input-csrf-defer' => __DIR__.'/snippets/kart/input-csrf-defer.php',
            'kart/kart' => __DIR__.'/snippets/kart/kart.php',
            'kart/login' => __DIR__.'/snippets/kart/login.php',
            'kart/login-magic' => __DIR__.'/snippets/kart/login-magic.php',
            'kart/logout' => __DIR__.'/snippets/kart/logout.php',
            'kart/order.pdf' => __DIR__.'/snippets/kart/order.pdf.php',
            'kart/paddle-checkout' => __DIR__.'/snippets/kart/paddle-checkout.php',
            'kart/product-card' => __DIR__.'/snippets/kart/product-card.php',
            'kart/product-json-ld' => __DIR__.'/snippets/kart/product-json-ld.php',
            'kart/profile' => __DIR__.'/snippets/kart/profile.php',
            'kart/signup-magic' => __DIR__.'/snippets/kart/signup-magic.php',
            'kart/snipcart-checkout' => __DIR__.'/snippets/kart/snipcart-checkout.php',
            'kart/sumup-checkout' => __DIR__.'/snippets/kart/sumup-checkout.php',
            'kart/turnstile-form' => __DIR__.'/snippets/kart/turnstile-form.php',
            'kart/turnstile-widget' => __DIR__.'/snippets/kart/turnstile-widget.php',
            'kart/wish-or-forget' => __DIR__.'/snippets/kart/wish-or-forget.php',
            'kart/wish-or-forget.htmx' => __DIR__.'/snippets/kart/wish-or-forget.htmx.php',
            'kart/wishlist' => __DIR__.'/snippets/kart/wishlist.php',
            'kerbs/inertia' => __DIR__.'/snippets/kerbs/inertia.php',
            'kerbs/layout' => __DIR__.'/snippets/kerbs/layout.php',
            'seo/head' => __DIR__.'/snippets/seo/head.php',
            'seo/schemas' => __DIR__.'/snippets/seo/schemas.php',
        ],
        'blueprints' => [
            'users/customer' => __DIR__.'/blueprints/users/customer.yml',
            'pages/order' => __DIR__.'/blueprints/pages/order.yml',
            'pages/orders' => __DIR__.'/blueprints/pages/orders.yml',
            'pages/product' => __DIR__.'/blueprints/pages/product.yml',
            'pages/products' => __DIR__.'/blueprints/pages/products.yml',
            'pages/stock' => __DIR__.'/blueprints/pages/stock.yml',
            'pages/stocks' => __DIR__.'/blueprints/pages/stocks.yml',
            'tabs/product-local' => __DIR__.'/blueprints/tabs/product-local.yml',
            'tabs/order-local' => __DIR__.'/blueprints/tabs/order-local.yml',
        ],
        'templates' => [
            'cart' => __DIR__.'/templates/cart.php',
            'kart' => __DIR__.'/templates/kart.php',
            'login' => __DIR__.'/templates/login.php',
            'order' => __DIR__.'/templates/order.php',
            'order.pdf' => __DIR__.'/templates/order.pdf.php',
            'order.zip' => __DIR__.'/templates/order.zip.php',
            'orders' => __DIR__.'/templates/orders.php',
            'payment' => __DIR__.'/templates/payment.php',
            'product' => __DIR__.'/templates/product.php',
            'products' => __DIR__.'/templates/products.php',
            'signup' => __DIR__.'/templates/signup.php',
            'stock' => __DIR__.'/templates/stock.php',
            'stocks' => __DIR__.'/templates/stocks.php',
        ],
    ]
);
